# Use a imagem do SDK do .NET Core para construir o aplicativo
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app

# Copie o projeto e restaure as dependências
COPY *.csproj ./
RUN dotnet restore

# Copie o restante do código e construa o aplicativo
COPY . ./
RUN dotnet publish -c Release -o out

# Use a imagem do ASP.NET Core para executar o aplicativo
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS runtime
WORKDIR /app
COPY --from=build /app/out ./
ENTRYPOINT ["dotnet", "DotNet.Docker.dll"]
